// template: [filename, name]
const placeableMap = new Map<string, string>([
  [
    "data/placeables/lizard/cowBarnSmall/cowBarnSmall.xml",
    "$l10n_storeItem_animalBarnCowSmall",
  ],
  [
    "data/placeables/lizard/dieselTanks/level01/dieselTanksLevel01.xml",
    "$l10n_storeItem_dieselTank01",
  ],
  [
    "data/placeables/lizard/dieselTanks/level02/dieselTanksLevel02.xml",
    "$l10n_storeItem_dieselTank02",
  ],
  [
    "data/placeables/lizard/dieselTanks/level03/dieselTanksLevel03.xml",
    "$l10n_storeItem_dieselTank03",
  ],
  [
    "data/placeables/lizard/greenhouses/greenhouseLarge/greenhouseLarge.xml",
    "$l10n_shopItem_greenhouseLarge",
  ],
  [
    "data/placeables/lizard/greenhouses/greenhouseMedium/greenhouseMedium.xml",
    "$l10n_shopItem_greenhouseMedium",
  ],
  [
    "data/placeables/lizard/greenhouses/greenhouseSmall/greenhouseSmall.xml",
    "$l10n_shopItem_greenhouseSmall",
  ],
  ["data/placeables/lizard/hayLoft/hayLoft.xml", "$l10n_shopItem_hayLoft"],
  [
    "data/placeables/lizard/horseBarnSmall/horseBarnSmall.xml",
    "$l10n_storeItem_animalBarnHorseSmall",
  ],
  [
    "data/placeables/lizard/liquidManureTank/baseTank/baseTank.xml",
    "$l10n_storeItem_liquidManureTank",
  ],
  [
    "data/placeables/lizard/liquidManureTank/extensionLarge/extensionLarge.xml",
    "$l10n_storeItem_liquidManureTankExtensionLarge",
  ],
  [
    "data/placeables/lizard/liquidManureTank/extensionSmall/extensionSmall.xml",
    "$l10n_storeItem_liquidManureTankExtensionSmall",
  ],
  [
    "data/placeables/lizard/pigBarnSmall/pigBarnSmall.xml",
    "$l10n_storeItem_animalBarnPigSmall",
  ],
  [
    "data/placeables/lizard/productionPoints/bakeryEU/bakeryEU.xml",
    "$l10n_shopItem_bakery",
  ],
  [
    "data/placeables/lizard/productionPoints/bakeryUS/bakeryUS.xml",
    "$l10n_shopItem_bakery",
  ],
  [
    "data/placeables/lizard/productionPoints/carpenterEU/carpenterEU.xml",
    "$l10n_shopItem_carpenter",
  ],
  [
    "data/placeables/lizard/productionPoints/carpenterUS/carpenterUS.xml",
    "$l10n_shopItem_carpenter",
  ],
  [
    "data/placeables/lizard/productionPoints/cerealFactory/cerealFactory.xml",
    "$l10n_shopItem_cerealFactory",
  ],
  [
    "data/placeables/lizard/productionPoints/dairyEU/dairyEU.xml",
    "$l10n_shopItem_dairy",
  ],
  [
    "data/placeables/lizard/productionPoints/dairyUS/dairyUS.xml",
    "$l10n_shopItem_dairy",
  ],
  [
    "data/placeables/lizard/productionPoints/grainMill/grainMill.xml",
    "$l10n_shopItem_grainMill",
  ],
  [
    "data/placeables/lizard/productionPoints/oilPlant/oilPlant.xml",
    "$l10n_shopItem_oilMill",
  ],
  [
    "data/placeables/lizard/productionPoints/raisinFactory/raisinFactory.xml",
    "$l10n_shopItem_grapeProcessing",
  ],
  [
    "data/placeables/lizard/productionPoints/spinneryEU/spinneryEU.xml",
    "$l10n_shopItem_spinnery",
  ],
  [
    "data/placeables/lizard/productionPoints/spinneryUS/spinneryUS.xml",
    "$l10n_shopItem_spinnery",
  ],
  [
    "data/placeables/lizard/productionPoints/sugarMill/sugarMill.xml",
    "$l10n_shopItem_sugarMill",
  ],
  [
    "data/placeables/lizard/productionPoints/tailorShop/tailorShop.xml",
    "$l10n_shopItem_tailorShop",
  ],
  [
    "data/placeables/lizard/sheepBarnSmall/sheepBarnSmall.xml",
    "$l10n_storeItem_animalBarnSheepSmall",
  ],
  [
    "data/placeables/lizard/waterTanks/level01/waterTankLevel01.xml",
    "$l10n_storeItem_waterTank01",
  ],
  [
    "data/placeables/mapAlpine/bga/alpsBGA.xml",
    "$l10n_shopItem_mapAlpine_biogasPlant",
  ],
  [
    "data/placeables/mapAlpine/cheeseFactory/cheeseFactory.xml",
    "Käserei Erlengrat",
  ],
  [
    "data/placeables/mapAlpine/chocolateFactory/chocolateFactory.xml",
    "Liechti Chocolatier",
  ],
  [
    "data/placeables/mapAlpine/grainSiloRailroad01/grainSiloRailroad01.xml",
    "Straig Lager",
  ],
  [
    "data/placeables/mapAlpine/grainSiloRailroad02/grainSiloRailroad02.xml",
    "GLW",
  ],
  [
    "data/placeables/mapAlpine/sellingStations/sellingStationMill01.xml",
    "$l10n_station_alpine_mill",
  ],
  [
    "data/placeables/mapAlpine/sellingStationWood/sellingStationWood.xml",
    "$l10n_station_alpine_sawmill",
  ],
  [
    "data/placeables/mapAlpine/sellingStationWool/sellingStationWool.xml",
    "$l10n_station_alpine_spinnery",
  ],
  [
    "data/placeables/mapFR/railroadSilo01/railroadSilo01.xml",
    "$l10n_station_fr_railroadSilo01",
  ],
  [
    "data/placeables/mapFR/railroadSilo02/railroadSilo02.xml",
    "$l10n_station_fr_railroadSilo02",
  ],
  [
    "data/placeables/mapFR/sellingStationBakery/sellingStationBakery.xml",
    "$l10n_station_fr_bakery",
  ],
  [
    "data/placeables/mapFR/sellingStationCheeseDairy/sellingStationCheeseDairy.xml",
    "$l10n_station_fr_cheeseDairy",
  ],
  [
    "data/placeables/mapFR/sellingStationGrainMill/sellingStationGrainMill.xml",
    "$l10n_station_fr_grainMill",
  ],
  [
    "data/placeables/mapFR/sellingStationWood/sellingStationWood.xml",
    "$l10n_station_fr_sawmill",
  ],
  [
    "data/placeables/mapFR/sellingStationWool/sellingStationWool.xml",
    "$l10n_station_fr_spinnery",
  ],
  [
    "data/placeables/mapUS/productionPointGrainMill/productionPointGrainMill.xml",
    "$l10n_station_us_grainMill",
  ],
  [
    "data/placeables/mapUS/railroadStorageSilo01/railroadStorageSilo01.xml",
    "$l10n_station_us_grainSiloRailroad01",
  ],
  [
    "data/placeables/mapUS/railroadStorageSilo02/railroadStorageSilo02.xml",
    "$l10n_station_us_grainSiloRailroad02",
  ],
  ["data/placeables/mapUS/sawmill/sawmill.xml", "$l10n_station_us_sawmill"],
  [
    "data/placeables/meridian/fertilizerBins1620/fertilizerBins1620.xml",
    "$l10n_shopItem_meridianFertilizerTank",
  ],
  [
    "data/placeables/meridian/flatBottomBin3608/flatBottomBin3608.xml",
    "Flat Bottom Bin 3608",
  ],
  [
    "data/placeables/meridian/flatBottomBin3609/flatBottomBin3609.xml",
    "Flat Bottom Bin 3609",
  ],
  [
    "data/placeables/meridian/fuelTank25000L/fuelTank25000L.xml",
    "$l10n_storeItem_dieselTank03",
  ],
  [
    "data/placeables/meridian/liquidFlatBottomTank1630/liquidFlatBottomTank1630.xml",
    "$l10n_shopItem_liquidFertilizerTank",
  ],
  ["data/placeables/neuero/nl1622_16000/nl1622_16000.xml", "NL16-22 - 16000"],
  ["data/placeables/neuero/nl1622_2000/nl1622_2000.xml", "NL16-22 - 2000"],
  ["data/placeables/neuero/nl1622_6000/nl1622_6000.xml", "NL16-22 - 6000"],
  ["data/placeables/planET/bga1mw/bga1mw.xml", "$l10n_storeItem_planET_bga1mw"],
  [
    "data/placeables/planET/bga250kw/bga250kw.xml",
    "$l10n_storeItem_planET_bga250kw",
  ],
  [
    "data/placeables/planET/bga500kw/bga500kw.xml",
    "$l10n_storeItem_planET_bga500kw",
  ],
  [
    "data/placeables/planET/bga99kw/bga99kw.xml",
    "$l10n_storeItem_planET_bga99kw",
  ],
  [
    "data/placeables/rudolfHormann/chickenBarnBig/chickenBarnBig.xml",
    "$l10n_storeItem_animalBarnChickenBig",
  ],
  [
    "data/placeables/rudolfHormann/cowBarnBig/cowBarnBig.xml",
    "$l10n_storeItem_animalBarnCowBig",
  ],
  [
    "data/placeables/rudolfHormann/cowBarnBig/cowBarnBigVector.xml",
    "$l10n_storeItem_animalBarnCowBigVector",
  ],
  [
    "data/placeables/rudolfHormann/cowBarnMedium/cowBarnMedium.xml",
    "$l10n_storeItem_animalBarnCowMedium",
  ],
  [
    "data/placeables/rudolfHormann/horseBarnBig/horseBarnBig.xml",
    "$l10n_storeItem_animalBarnHorseBig",
  ],
  [
    "data/placeables/rudolfHormann/horseBarnMedium/horseBarnMedium.xml",
    "$l10n_storeItem_animalBarnHorseMedium",
  ],
  [
    "data/placeables/rudolfHormann/pigBarnBig/pigBarnBig.xml",
    "$l10n_storeItem_animalBarnPigBig",
  ],
  [
    "data/placeables/rudolfHormann/pigBarnMedium/pigBarnMedium.xml",
    "$l10n_storeItem_animalBarnPigMedium",
  ],
  ["data/placeables/unia/farma/farma100/farma100.xml", "Farma 100"],
  ["data/placeables/unia/farma/farma150/farma150.xml", "Farma 150"],
  ["data/placeables/unia/farma/farma200/farma200.xml", "Farma 200"],
  ["data/placeables/unia/farma/farma250/farma250.xml", "Farma 250"],
  ["data/placeables/unia/farma/farma400/farma400.xml", "Farma 400 + Obi 1000"],
  ["data/placeables/unia/farma/farma500/farma500.xml", "Farma 500 + Obi 1000"],
  ["data/placeables/unia/farma/farma800/farma800.xml", "Farma 800 + Obi 1000"],
  ["data/placeables/unia/karma/karma16/karma16.xml", "Karma 16"],
]);

export default placeableMap;
